# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x0cnotification\"!\n\rNotifyRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"(\n\x12NotifyCountRequest\x12\x12\n\nuser_count\x18\x01 \x01(\x05\" \n\x0eNotifyResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xb2\x01\n\x13NotificationService\x12H\n\x0bNotifyLogin\x12\x1b.notification.NotifyRequest\x1a\x1c.notification.NotifyResponse\x12Q\n\x0fNotifyUserCount\x12 .notification.NotifyCountRequest\x1a\x1c.notification.NotifyResponseB\'\n#com.hsoaresdev.notification_serviceP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.hsoaresdev.notification_serviceP\001'
  _globals['_NOTIFYREQUEST']._serialized_start=36
  _globals['_NOTIFYREQUEST']._serialized_end=69
  _globals['_NOTIFYCOUNTREQUEST']._serialized_start=71
  _globals['_NOTIFYCOUNTREQUEST']._serialized_end=111
  _globals['_NOTIFYRESPONSE']._serialized_start=113
  _globals['_NOTIFYRESPONSE']._serialized_end=145
  _globals['_NOTIFICATIONSERVICE']._serialized_start=148
  _globals['_NOTIFICATIONSERVICE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
