# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import notification_pb2 as notification__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in notification_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NotificationServiceStub(object):
    """Notification service for user login events.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyLogin = channel.unary_unary(
                '/notification.NotificationService/NotifyLogin',
                request_serializer=notification__pb2.NotifyRequest.SerializeToString, # type: ignore
                response_deserializer=notification__pb2.NotifyResponse.FromString, # type: ignore
                _registered_method=True)
        self.NotifyUserCount = channel.unary_unary(
                '/notification.NotificationService/NotifyUserCount',
                request_serializer=notification__pb2.NotifyCountRequest.SerializeToString, # type: ignore
                response_deserializer=notification__pb2.NotifyResponse.FromString, # type: ignore
                _registered_method=True)


class NotificationServiceServicer(object):
    """Notification service for user login events.
    """

    def NotifyLogin(self, request, context):
        """Notifies about a user login via Server-Sent Events (SSE) broadcast.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyUserCount(self, request, context):
        """Sends the current total user count to be broadcast as an SSE 'user_count' event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyLogin,
                    request_deserializer=notification__pb2.NotifyRequest.FromString, # type: ignore
                    response_serializer=notification__pb2.NotifyResponse.SerializeToString, # type: ignore
            ),
            'NotifyUserCount': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyUserCount,
                    request_deserializer=notification__pb2.NotifyCountRequest.FromString, # type: ignore
                    response_serializer=notification__pb2.NotifyResponse.SerializeToString, # type: ignore
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notification.NotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('notification.NotificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotificationService(object):
    """Notification service for user login events.
    """

    @staticmethod
    def NotifyLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/notification.NotificationService/NotifyLogin',
            notification__pb2.NotifyRequest.SerializeToString, # type: ignore
            notification__pb2.NotifyResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyUserCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/notification.NotificationService/NotifyUserCount',
            notification__pb2.NotifyCountRequest.SerializeToString, # type: ignore
            notification__pb2.NotifyResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
